config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: "sessions",
  	registrations: "registrations",
  	omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  resources :users, only: [:show]
  resources :informations
    
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
	belongs_to :user
	
	validates :weight, presence: true, numericality: { greater_than_or_equal_to: 30, less_than_or_equal_to: 200 }
	validates :height, presence: true, numericality: { greater_than_or_equal_to: 140, less_than_or_equal_to: 200 }
	validates :age, presence: true
	validates :gender, presence: true
	validates :activity_level, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
	validates :user_id, presence: true
	validates :diet_plan, presence: true
	validates :result, presence: true
	validates :protein, presence: true
	validates :carb, presence: true
	validates :fat, presence: true
	  
	def self.calBMR(information)
	  x = (10*information.weight) + (6.25*information.height) - (5*information.age)
    if information.gender == 1
      information.bmr = x + 5
    else
	    information.bmr = x - 161
    end
	end
	
	def self.calResult(information)
	  if information.activity_level == 1
	    base_cal = information.bmr * 1.2
    elsif information.activity_level == 2
      base_cal = information.bmr * 1.375
    elsif information.activity_level == 3
      base_cal = information.bmr * 1.55
    elsif information.activity_level == 4
      base_cal = information.bmr * 1.725
    else
      base_cal = information.bmr * 2
	  end  
	  
	  if information.diet_plan == 1
	    information.result = base_cal
    elsif information.diet_plan == 2
      information.result = base_cal + (base_cal * 0.2)
    else 
      information.result = base_cal - (base_cal * 0.2)
    end
	end
	
	def self.calMacros(information)
	  if information.activity_level == (1 || 2)
      information.protein = information.weight * 1.4
    elsif information.activity_level == (3 || 4)
      information.protein = information.weight * 1.6
    else 
      information.protein = information.weight * 1.8
    end
    # 25% of daily calorie intake is fat
    information.fat = (information.result * 0.25) / 9
    
    information.carb = (information.result - (information.protein * 4 + information.fat * 9)) /4
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
	attr_accessor :login
  
	validates :username,
 		presence: true, 
 		uniqueness: {
 			case_sensitive: false
   		}
  # Only allow letter, number, underscore and punctuation.
	validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  
  def self.find_first_by_auth_conditions(warden_conditions)
		conditions = warden_conditions.dup
		if login = conditions.delete(:login)
		  where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
		else
		  where(conditions).first
		end
	end
	
	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
    end
	end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session
  
  before_action :destroy_session
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  def destroy_session
    request.session_options[:skip] = true
  end
  
  def not_found
    return api_error(status: 404, errors: 'Not Found')
  end
end

app/controllers/api/v1/informations_controller.rb
class Api::V1::InformationsController < Api::V1::BaseController
  def show
    information = Information.find(params[:id])
    
    render(json: Api::V1::InformationSerializer.new(information).to_json)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def show
    user = User.find(params[:id])
    
    render(json: Api::V1::UserSerializer.new(user).to_json)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
  	update_attrs = [:username, :password, :password_confirmation, :current_password]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs) 
    devise_parameter_sanitizer.permit(:account_update, keys: update_attrs) 
  end
  
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
	end
	
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
	before_action :authenticate_user!
	
	def index
	  @informations = Information.where(user_id: current_user.id).all
	end
	
	def new
		@information = Information.new
	end
	
	def create
		@information = Information.new(information_params)
		@information.user_id = current_user.id
		Information.calBMR(@information)
		Information.calResult(@information)
		Information.calMacros(@information)
		if @information.save
			flash[:success] = "Your information has been saved"
			redirect_to informations_path
		else
			render 'new'
		end
	end
	
	def show
		@information = Information.find(params[:id])
	end
	
	private
		
		def information_params
			params.require(:information).permit(:weight, :height, :age, :gender, :activity_level, :user_id, :diet_plan)
		end
		
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController 
  respond_to :html, :js
  
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	
	def show
		@user = current_user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
	def nav_link text, link, icon={}
    icon = {
      size: "1x"
    }.merge(icon)

    content = link_to icon[:type].present? ? fa_icon(icon[:type].to_s, text: text, class: icon[:size].to_s) : text, link

    if current_page? link
      content_tag :li, class: "active" do
        content
      end
    else
      content_tag(:li) do
        content
      end
    end
  end
  
  
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/home/index.html.erb
<h1>Welcome to MacrosTracker</h1>

<div class="btn-count">
  <% if user_signed_in? %>
    <%= link_to "Count your daily macros", new_information_path, class: 'btn btn-md btn-primary' %>
    
  <% else %>
    <div class="text-center" id="des"><h4>Track your fitness journey and much more</h4></div>
    <%= link_to "Subcribe now", new_user_registration_path, class: 'btn btn-md btn-success' %>
  <% end %>
</div>

app/views/informations/_form.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2" id="form">
			<h3 class="text-center">Please enter your informations</h3>
			<%= form_for(@information, url: {action: "create"}) do |f| %>
				<div class="form-group", id= "Age" >
					<%= f.label :age %><br/>
					<%= f.text_field :age, class: 'form-control', placeholder: "Your age right now"%>
				</div>
				
				<div class="form-group", id= "weight" >
					<%= f.label :weight %><br/>
					<%= f.text_field :weight, class: 'form-control', placeholder: "Your weight in kilograms"%>
				</div>
		
				<div class="form-group", id= "height">
					<%= f.label :height %><br/>
					<%= f.text_field :height, class: 'form-control', placeholder: "Your height in centimeters" %>
				</div>
		
				<div class="gender">
				  <h5><strong>Choose your gender:</strong></h5>
					<%= f.radio_button(:gender, 1) %>
					<%= f.label(:gender, "male") %>
					&nbsp
					<%= f.radio_button(:gender, 2) %>
					<%= f.label(:gender, "female") %>
				</div>
				
				<div class="activity">
					<%= f.label :activity_level %>:&nbsp&nbsp
					<%= f.select :activity_level, options_for_select([['', 0],['Sedentary', 1], ['Lightly Active', 2], ['Moderately Active', 3], ['Very Active', 4], ['Extremely Active', 5]]) %>
				</div>
				
				<div class="diet">
				  <h5><strong>Choose your diet plan:</strong></h5>
					<%= f.radio_button(:diet_plan, 1) %>
					<%= f.label(:diet_plan, "Weight maintenance") %>
					&nbsp
					<%= f.radio_button(:diet_plan, 2) %>
					<%= f.label(:diet_plan, "Weight gain") %>
					&nbsp
					<%= f.radio_button(:diet_plan, 3) %>
					<%= f.label(:diet_plan, "Weight loss") %>
				</div>
				
				<div class="btn-count">
				  <%= f.submit "Calculate", class: 'btn btn-primary btn-md' %>
			  </div>
			<% end %>
		</div>
	</div>
</div>

app/views/informations/index.html.erb
<div class="container-fluid" id="info">
  <% @informations.each do |info| %>
    <div class="jumbotron" id = "jumb">
      <%= link_to info.created_at, information_path(info), class: 'text-center' %><br/><br/>
      
      Age: <%= info.age %>, Weight: <%= info.weight %>kg, Height: <%= info.height %>cm
    </div>
  <% end %>
</div>

app/views/informations/new.html.erb
<%= render 'shared/errors' %>

<%= render 'form' %>

app/views/informations/show.html.erb
<div class="jumbotron">  
  <h2 class="text-center">Your result</h2>
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th class="text-center">Calorie intake</th>
        <th class="text-center">Protein</th>
        <th class="text-center">Carb</th>
        <th class="text-center">Fat</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-center"><strong><%= "%.2f" % @information.result %> kcal/day</strong></td>
      
      
        <td class="text-center"><strong><%= "%.2f" % @information.protein %> gr/day</strong></td>
      
      
        <td class="text-center"><strong><%= "%.2f" % @information.carb %> gr/day</strong></td>
      
      
        <td class="text-center"><strong><%= "%.2f" % @information.fat %> gr/day</strong></td>
      </tr>
      
    </tbody>
  </table>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy, Minh Nguyen 2017. All Rights Reserved</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
        <a class="close" data-dismiss="alert">&#215,</a>
      </div>
    <% end %>  
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="main-nav navbar-transparent" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-collapsable-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'MacrosTracker', "/", class: 'navbar-brand' %>
		</div>
      
  	
  	<div class="collapse navbar-collapse" id="navbar-collapse">
  	  <ul class="nav navbar-nav ">
        <li><%= link_to "About", "" %> <span class="sr-only">(current)</span></li>
        <li><%= link_to "Articles", "" %> <span class="sr-only">(current)</span></li>
        <li><%= link_to "Products", "" %> <span class="sr-only">(current)</span></li>
      </ul>
  		<ul class="nav navbar-nav navbar-right">
  		  <% if user_signed_in? %>
    			<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon "user", class: "fa-1x" %> <strong><%= current_user.username %></strong> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit settings", edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            </ul>
        	</li>
  		
        <% else %>
  	
    		  <li class="active">
    			  <%= link_to "Log in", new_user_session_path, remote: true  %>
    			</li>
  			<% end %>
  			
  		</ul>
  	</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Macrostracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="mymodal" class="modal fade" ></div>
		<%= render 'layouts/navigation' %>
		<div class="container">
		  <%= render 'layouts/messages' %>

		  <%= yield %>
		</div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if @information.errors.any? %>
	<div class="row">
		<div class="alert alert-danger col-md-8 col-md-offset-2">
			<h5>Please correct the following errors:</h5>
			<ul>
				<% @information.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>